Build UC Server image

diff --git a/docker/bin/build-uc-cli-docker b/docker/bin/build-uc-cli-docker
--- a/docker/bin/build-uc-cli-docker
+++ b/docker/bin/build-uc-cli-docker
@@ -13,10 +13,15 @@ cd "$project_dir"
 
 if [[ -r "$docker_file" ]]; then
     echo "Building docker container $container_name:$container_version from Dockerfile $docker_file"
-    docker buildx build --progress=plain -t "$container_name:$container_version" -f "$docker_file" .
+    docker buildx build \
+      --progress=plain \
+      --no-cache \
+      --build-arg unitycatalog_version="$container_version" \
+      -t "$container_name:$container_version" \
+      -f "$docker_file" .
 else
-    echo -e "Dockerfile $docker_file not found in the project's root directory."
-    exit
+    echo -e "Dockerfile $docker_file not found in $project_dir. Exiting..."
+    exit 1
 fi
 
 echo "Returning to base directory $current_dir"
diff --git a/docker/bin/build-uc-server-docker b/docker/bin/build-uc-server-docker
--- a/docker/bin/build-uc-server-docker
+++ b/docker/bin/build-uc-server-docker
@@ -2,24 +2,26 @@
 set -ex;
 
 current_dir=$(pwd)
-script_dir=$(dirname $0)
-project_dir=$(dirname $(dirname $(realpath $script_dir)))
+script_dir=$(dirname "$0")
+project_dir=$(dirname "$(dirname "$(realpath "$script_dir")")")
+docker_file="Dockerfile"
 container_name="unitycatalog"
 container_version=$(< "$project_dir/version.sbt" cut -d '"' -f2)
 
 echo "Changing directory to $project_dir"
 cd "$project_dir"
 
-if [[ -r Dockerfile ]]; then
+if [[ -r "$docker_file" ]]; then
     echo "Building docker container $container_name:$container_version"
     docker buildx build \
       --progress=plain \
       --no-cache \
       --build-arg unitycatalog_version="$container_version" \
-      -t "$container_name:$container_version" .
+      -t "$container_name:$container_version" \
+      -f "$docker_file" .
 else
-    echo "Dockerfile not found in $project_dir."
-    exit
+    echo "Dockerfile $docker_file not found in $project_dir. Exiting..."
+    exit 1
 fi
 
 echo "Returning to base directory $current_dir"
