Fix the Dockerfiles to an MVP

diff --git a/docker/build-uc/Dockerfile b/docker/build-uc/Dockerfile
--- a/docker/build-uc/Dockerfile
+++ b/docker/build-uc/Dockerfile
@@ -1,52 +1,44 @@
-FROM eclipse-temurin:17-jdk-jammy AS build_uc
+FROM eclipse-temurin:17-jdk-alpine AS build_uc
 
+# Install any required packages
+RUN <<EOF
+    set -ex;
+    apk update;
+    apk upgrade; 
+    apk add bash git;
+EOF
 
-ARG unitycatalog_uid=185
+# Define the shell used within the container
+SHELL ["/bin/bash", "-i", "-c", "-o", "pipefail"] 
+
 ARG unitycatalog_home="/opt/unitycatalog"
-
-RUN set -ex; \
-    apt-get update; \
-    apt-get install -y bash git; \
-    # Remove temporary files to reduce image size
-    rm -rf /var/lib/apt/lists/*
-
-
-# COPY ../../ /opt/unitycatalog
-# COPY build_uc.sh /opt/unitycatalog/build_uc.sh
-
-
-WORKDIR /opt/unitycatalog
-COPY <<"EOF" /opt/unitycatalog/build_uc.sh
-#!/usr/bin/env bash
-set -ex;
-
-REPO_DIR="${unitycatalog_home}/repo"
-REPO_URL="https://github.com/unitycatalog/unitycatalog.git"
+ARG unitycatalog_repo="${unitycatalog_home}/repo"
+ARG unitycatalog_github="https://github.com/unitycatalog/unitycatalog.git"
+# Specify which version to pull ex.: 0.1.0
+ARG unitycatalog_version="main"
+# Specify any custom parameters necessary to generate
+# the Uber-Jar by SBT. 
+# Note: The default allocated heam memory size is too small
+# and will cause the process to fail when attempting to compile
+# and generate the Uber-Jar. Therefore it is important to choose
+# a size large enough for the compiler to run. 
+ARG sbt_args="-J-Xmx5G"
 
 
-[ ! -d $REPO_DIR ] && mkdir -p $REPO_DIR
-
-cd $REPO_DIR
-
-if [ -d ".git" ]; then
-    echo "Repository already cloned. Pulling latest changes..."
-    git pull
-else
-    echo "Cloning repository..."
-    git clone $REPO_URL .
-fi
-
-
-build/sbt -v -d -J-Xmx5G assembly
-
+# Create temporary directories for initialization files
+RUN <<-EOF 
+    set -ex;
+    mkdir -p "${unitycatalog_repo}";
+    cd "${unitycatalog_repo}";
+    git clone ${unitycatalog_github} --branch ${unitycatalog_version} --single-branch .;
 EOF
 
-RUN <<EOF 
-#!/usr/bin/env bash
-set -ex;
-pwd
-chmod +x build_uc.sh
-. build_uc.sh
+WORKDIR "${unitycatalog_repo}"
+
+RUN <<-EOF
+    #!/usr/bin/env bash
+    set -ex;
+    build/sbt ${sbt_args} assembly
 EOF
 
-CMD ["echo", "Hello"]
+ENTRYPOINT ["/usr/bin/env", "bash"]
diff --git a/docker/run-uc/Dockerfile b/docker/run-uc/Dockerfile
--- a/docker/run-uc/Dockerfile
+++ b/docker/run-uc/Dockerfile
@@ -16,45 +16,93 @@ ARG unitycatalog_repo="${unitycatalog_home}/repo"
 ARG unitycatalog_jar="server/target"
 ARG unitycatalog_etc="etc"
 ARG unitycatalog_bin="bin"
+ARG unitycatalog_user_name="unitycatalog"
+ARG unitycatalog_user_home="home"
+ARG unitycatalog_user_basedir="${unitycatalog_home}/${unitycatalog_user_home}"
 
 ENV SERVER_TARGET_DIR="${unitycatalog_home}/${unitycatalog_jar}"
+ENV UC_SERVER_BIN="${unitycatalog_home}/${unitycatalog_bin}/start-uc-server"
 
-# Create temporary directories for initialization files
-RUN <<EOF 
+# Create the UC directories
+RUN <<-EOF 
     set -ex;
+    mkdir -p "${unitycatalog_home}";
     mkdir -p "${unitycatalog_home}/${unitycatalog_jar}";
     mkdir -p "${unitycatalog_home}/${unitycatalog_etc}";
     mkdir -p "${unitycatalog_home}/${unitycatalog_bin}";
+    mkdir -p "${unitycatalog_home}/${unitycatalog_user_home}";
 EOF
 
-COPY --from=unitycatalogue_builder:0.1.0 "${unitycatalog_repo}/${unitycatalog_jar}/*.jar" "${unitycatalog_home}/${unitycatalog_jar}/"
-COPY --from=unitycatalogue_builder:0.1.0 "${unitycatalog_repo}/${unitycatalog_etc}" "${unitycatalog_home}/${unitycatalog_etc}/"
+
+# Create system group and user for Unity Catalog
+# ENsure the user created has their HOME pointing to the volume
+# created to persist user data and the sbt cached files that 
+# are created as a result of compiling the unity catalog.
+# This also ensures that the container can run independently from
+# the storage, so we can have ephemeral docker instances with --rm
+# and still be able to run the unity catalog each time without problems.
+RUN <<-EOF
+    #!/usr/bin/env bash
+    set -ex;
+    addgroup --system --gid "${unitycatalog_uid}" "${unitycatalog_user_name}";
+    adduser --system --uid "${unitycatalog_uid}" \
+            --ingroup "${unitycatalog_user_name}" \
+            --home "${unitycatalog_user_basedir}" \
+            --shell "$(/usr/bin/env bash)" \
+            "${unitycatalog_user_name}";
+EOF
+
+# Define volume to persist Unity Catalog data
+VOLUME  ${unitycatalog_home}
 
 WORKDIR "$unitycatalog_home"
 
-ENV UC_SERVER_BIN="${unitycatalog_home}/${unitycatalog_bin}/start-uc-server"
-COPY <<"EOF" "${UC_SERVER_BIN}"
-#!/usr/bin/env bash
+# Copy the Uber-Jar from the previous stage
+COPY --from=unitycatalogue_builder:0.1.0 "${unitycatalog_repo}/${unitycatalog_jar}/*.jar" "${unitycatalog_home}/${unitycatalog_jar}/"
 
-set -ex;
+# Copy the etc folder which contains the config files and the data folder
+COPY --from=unitycatalogue_builder:0.1.0 "${unitycatalog_repo}/${unitycatalog_etc}" "${unitycatalog_home}/${unitycatalog_etc}/"
 
-SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
-ROOT_DIR="$(dirname "$SCRIPT_DIR")"
+# Create the script that executes the server
+# The script looks for the JAR automatially and saves its
+# path into a variable then runs the server.
+COPY <<-"EOF" "${UC_SERVER_BIN}"
+    #!/usr/bin/env bash
+    set -ex;
 
-SERVER_JAR=$(find "$SERVER_TARGET_DIR" -name "unitycatalog-server*.jar" | head -n 1)
-if [ -z "$SERVER_JAR" ]; then
-    echo "Server JAR not found starting with 'unitycatalog-server*' in the target directory '$SERVER_TARGET_DIR'."
-    exit 1
-fi
+    SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
+    ROOT_DIR="$(dirname "$SCRIPT_DIR")"
 
-relative_path_to_jar="${SERVER_JAR//"$ROOT_DIR/"/}"
+    # Find the jar and store its absolute path into a variable
+    SERVER_JAR=$(find "$SERVER_TARGET_DIR" -name "unitycatalog-server*.jar" | head -n 1)
+    if [ -z "$SERVER_JAR" ]; then
+        echo "Server JAR not found starting with 'unitycatalog-server*' in the target directory '$SERVER_TARGET_DIR'."
+        exit 1
+    fi
 
-SERVER_JAVA_COMMAND="java -jar $relative_path_to_jar"
+    # Create relative path to jar so that it is able to find the 
+    # configuration files in etc/conf/...
+    relative_path_to_jar="${SERVER_JAR//"$ROOT_DIR/"/}"
 
-$SERVER_JAVA_COMMAND $@ || exit
+    # Prepare the command to be executed
+    SERVER_JAVA_COMMAND="java -jar $relative_path_to_jar"
 
+    # Execute the jar / ie Run the server
+    $SERVER_JAVA_COMMAND $@ || exit
 EOF
 
-RUN chmod +x $UC_SERVER_BIN
+
+# Set ownership of directories and Unity Catalog home directory to a less
+# priviledged user
+RUN <<-"EOF"
+    #!/usr/bin/env bash
+    set -ex;
+    chown -R "${unitycatalog_user_name}":"${unitycatalog_user_name}" "$unitycatalog_home";
+    chmod u+x "$UC_SERVER_BIN";
+EOF
+
+
+# Set the user for the container process
+USER "${unitycatalog_user_name}"
 
 ENTRYPOINT exec ${UC_SERVER_BIN}
